/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagIndexRouteImport } from './routes/tag/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as TagNewRouteImport } from './routes/tag/new'
import { Route as ProductNewRouteImport } from './routes/product/new'
import { Route as TagEditIdRouteImport } from './routes/tag/edit/$id'
import { Route as ProductEditIdRouteImport } from './routes/product/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagIndexRoute = TagIndexRouteImport.update({
  id: '/tag/',
  path: '/tag/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagNewRoute = TagNewRouteImport.update({
  id: '/tag/new',
  path: '/tag/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductNewRoute = ProductNewRouteImport.update({
  id: '/product/new',
  path: '/product/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TagEditIdRoute = TagEditIdRouteImport.update({
  id: '/tag/edit/$id',
  path: '/tag/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductEditIdRoute = ProductEditIdRouteImport.update({
  id: '/product/edit/$id',
  path: '/product/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/new': typeof ProductNewRoute
  '/tag/new': typeof TagNewRoute
  '/product': typeof ProductIndexRoute
  '/tag': typeof TagIndexRoute
  '/product/edit/$id': typeof ProductEditIdRoute
  '/tag/edit/$id': typeof TagEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/new': typeof ProductNewRoute
  '/tag/new': typeof TagNewRoute
  '/product': typeof ProductIndexRoute
  '/tag': typeof TagIndexRoute
  '/product/edit/$id': typeof ProductEditIdRoute
  '/tag/edit/$id': typeof TagEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/new': typeof ProductNewRoute
  '/tag/new': typeof TagNewRoute
  '/product/': typeof ProductIndexRoute
  '/tag/': typeof TagIndexRoute
  '/product/edit/$id': typeof ProductEditIdRoute
  '/tag/edit/$id': typeof TagEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product/new'
    | '/tag/new'
    | '/product'
    | '/tag'
    | '/product/edit/$id'
    | '/tag/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/new'
    | '/tag/new'
    | '/product'
    | '/tag'
    | '/product/edit/$id'
    | '/tag/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/product/new'
    | '/tag/new'
    | '/product/'
    | '/tag/'
    | '/product/edit/$id'
    | '/tag/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductNewRoute: typeof ProductNewRoute
  TagNewRoute: typeof TagNewRoute
  ProductIndexRoute: typeof ProductIndexRoute
  TagIndexRoute: typeof TagIndexRoute
  ProductEditIdRoute: typeof ProductEditIdRoute
  TagEditIdRoute: typeof TagEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/': {
      id: '/tag/'
      path: '/tag'
      fullPath: '/tag'
      preLoaderRoute: typeof TagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/new': {
      id: '/tag/new'
      path: '/tag/new'
      fullPath: '/tag/new'
      preLoaderRoute: typeof TagNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/new': {
      id: '/product/new'
      path: '/product/new'
      fullPath: '/product/new'
      preLoaderRoute: typeof ProductNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/edit/$id': {
      id: '/tag/edit/$id'
      path: '/tag/edit/$id'
      fullPath: '/tag/edit/$id'
      preLoaderRoute: typeof TagEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/edit/$id': {
      id: '/product/edit/$id'
      path: '/product/edit/$id'
      fullPath: '/product/edit/$id'
      preLoaderRoute: typeof ProductEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductNewRoute: ProductNewRoute,
  TagNewRoute: TagNewRoute,
  ProductIndexRoute: ProductIndexRoute,
  TagIndexRoute: TagIndexRoute,
  ProductEditIdRoute: ProductEditIdRoute,
  TagEditIdRoute: TagEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
